define(function(){

function Table(){
	this._bindClickRow();
}

Table.prototype = {

	_bindClickRow : function(){
		var self = this;
		$('.fold-row').on('click', function(e){
			var target = $( e.target );
			if( target.hasClass('btn') ) return;
			if( target.hasClass('checkone') ) return;
			if( target.parent().hasClass('fold-ctrl') ) return;

			var row = $( e.currentTarget );

			if( row.hasClass('inserted') ){				
				row.removeClass('inserted');
				$('.insert-tr').remove();
			}else{
				if( $('.insert-tr').length ) $('.insert-tr').remove();
				row.siblings('.inserted').removeClass('inserted');
				row.addClass('inserted');

				var pageName = $('#page-name').attr('data-page-name');
				if( pageName == '0043') self._insertRow0043( row );
				if( pageName == '0025') self._insertRow0025( row );
				if( pageName == '0054') self._insertRow0054( row );
				if( pageName == '0113') self._insertRow0113( row );
				if( pageName == '0119') self._insertRow0119( row );
				if( pageName == '0135') self._insertRow0135( row );
			}			
		});
	},

	_insertRow0043 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="9">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>影片资料</li>'
		+'			<li>分集资料</li>'
		+'			<li>视频信息</li>'
		+'			<li>转码信息</li>'
		+'			<li>标签信息</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-clm">'
		+'					<img src="../img/poster.jpg">'
		+'				</div>'
		+'				<div class="insert-clm">'
		+'					<p>'
		+'						<span class="bold">影片ID：</span>'
		+'						<span>asdfas</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">影片名：</span>'
		+'						<span>sdfsdf</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">集数：</span>'
		+'						<span>12</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">评分：</span>'
		+'						<span>10</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">影视分类：</span>'
		+'						<span>社教</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">剧情分类：</span>'
		+'						<span>no</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">剧情分类：</span>'
		+'						<span>no</span>'
		+'					</p>'
		+'					<p>'
		+'						<span class="bold">剧情分类：</span>'
		+'						<span>no</span>'
		+'					</p>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'				<div class="insert-disc">'
		+'					<p><span class="bold" title="简介：</span>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情...">简介：</span>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情...</p>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<table class="eps-info">'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>分集名称</th>'
		+'							<th>分集号</th>'
		+'							<th>分集嘉宾</th>'
		+'							<th>分集剧情</th>'
		+'							<th>分集海报</th>'
		+'							<th>分集点评</th>'
		+'							<th>分集状态</th>'
		+'							<th>操作</th>'
		+'						</tr>'
		+'						<tr class="eps-row">'
		+'							<td>钢的琴1</td>'
		+'							<td>01</td>'
		+'							<td>扎根梦</td>'
		+'							<td class="eps-disc" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情</div></td>'
		+'							<td class="eps-img">'
		+'								<div><img src="../img/eps.jpg"></div>'
		+'							</td>'
		+'							<td class="eps-cmt" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮</div></td>'
		+'							<td>启用</td>'
		+'							<td>'
		+'								<div class="fold-ctrl clearfix">'
		+'									<a class="fold-edit" title="编辑" href="0046.html"></a>'
		+'								</div>'
		+'							</td>'
		+'						</tr>'
		+'						<tr class="eps-row">'
		+'							<td>钢的琴1</td>'
		+'							<td>01</td>'
		+'							<td>扎根梦</td>'
		+'							<td class="eps-disc" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情</div></td>'
		+'							<td class="eps-img">'
		+'								<div><img src="../img/eps.jpg"></div>'
		+'							</td>'
		+'							<td class="eps-cmt" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮</div></td>'
		+'							<td>启用</td>'
		+'							<td>'
		+'								<div class="fold-ctrl clearfix">'
		+'									<a class="fold-edit" title="编辑" href="0046.html"></a>'
		+'								</div>'
		+'							</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<table class="vid-info">'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>供应商</th>'
		+'							<th>AssertID</th>'
		+'							<th>视频名称</th>'
		+'							<th>码率</th>'
		+'							<th>分辨率</th>'
		+'							<th>视频位置</th>'
		+'							<th>缓存状态</th>'
		+'							<th>发布状态</th>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td class="copy-url">复制链接</td>'
		+'							<td>待缓存</td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td class="copy-url">复制链接</td>'
		+'							<td>待缓存</td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<table class="video-transfer">'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>任务ID</th>'
		+'							<th>AssertID</th>'
		+'							<th>视频名称</th>'
		+'							<th>码率</th>'
		+'							<th>分辨率</th>'
		+'							<th>转码地址</th>'
		+'							<th>类型</th>'
		+'							<th>状态</th>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td class="copy-url">复制链接</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>转码完成</td>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td class="copy-url">复制链接</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>转码完成</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-tag">'
		+'					<span>标签名称<i class="tag-cross"></i></span>'
		+'					<span>标签名<i class="tag-cross"></i></span>'
		+'					<span>标签名称标签名称标签名称<i class="tag-cross"></i></span>'
		+'					<span>标签名<i class="tag-cross"></i></span>'
		+'					<span>标签<i class="tag-cross"></i></span>'
		+'					<span>标签<i class="tag-cross"></i></span>'
		+'					<span class="insert-add-tag" title="添加标签">+</span>'
		+'				</div>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();
	},

	_insertRow0025 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="11">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>基本信息</li>'
		+'			<li>DVB播放信息</li>'
		+'			<li>多屏播放信息</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">sdfsdf</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频asdfasdf道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多adsf屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/chaddddnnel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/chanddnel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">Bdd</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京ddd频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多dd屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channddel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWYsdf.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">BTV文艺</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();
	},

	_insertRow0054 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="13">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>影片资料</li>'
		+'			<li>子集资料</li>'
		+'			<li>视频信息</li>'
		+'			<li>转码信息</li>'
		+'			<li>标签信息</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">sdfsdf</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">北京频asdfasdf道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">多adsf屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">简介：</div>'
		+'					<div class="insert-r">/chadd23423ddd_</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">/c手动阀第三方.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<table class="eps-info">'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>影片名称</th>'
		+'							<th>影片ID</th>'
		+'							<th>嘉宾</th>'
		+'							<th>剧情</th>'
		+'							<th>海报</th>'
		+'							<th>短评</th>'
		+'							<th>操作</th>'
		+'						</tr>'
		+'						<tr class="eps-row">'
		+'							<td>钢的琴1</td>'
		+'							<td>01</td>'
		+'							<td>扎根梦</td>'
		+'							<td class="eps-disc" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情</div></td>'
		+'							<td class="eps-img">'
		+'								<div><img src="../img/eps.jpg"></div>'
		+'							</td>'
		+'							<td class="eps-cmt" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮</div></td>'
		+'							<td>'
		+'								<div class="fold-ctrl clearfix">'
		+'									<a class="fold-edit" title="编辑" href="0057.html"></a>'
		+'									<div class="fold-del" title="删除"></div>'
		+'									<a class="fold-pic" title="换图" href="0059.html"></a>'
		+'									<div class="fold-up" title="发布"></div>'
		+'								</div>'
		+'							</td>'
		+'						</tr>'
		+'						<tr class="eps-row">'
		+'							<td>钢的琴1</td>'
		+'							<td>01</td>'
		+'							<td>扎根梦</td>'
		+'							<td class="eps-disc" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮助用钢铁为女儿打造出一架钢琴的故事，通过小人物幽默与艰辛，展露一段感人至深的亲情和友情</div></td>'
		+'							<td class="eps-img">'
		+'								<div><img src="../img/eps.jpg"></div>'
		+'							</td>'
		+'							<td class="eps-cmt" title="《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮"><div>《钢的琴》讲述了一位父亲为了女儿的音乐梦想而不断艰苦努力，最后通过身边朋友的帮</div></td>'
		+'							<td>'
		+'								<div class="fold-ctrl clearfix">'
		+'									<a class="fold-edit" title="编辑" href="0046.html"></a>'
		+'									<div class="fold-del" title="删除"></div>'
		+'									<a class="fold-pic" title="换图" href="0059.html"></a>'
		+'									<div class="fold-up" title="发布"></div>'
		+'								</div>'
		+'							</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<table>'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>供应商</th>'
		+'							<th>AssertID</th>'
		+'							<th>视频名称</th>'
		+'							<th>码率</th>'
		+'							<th>分辨率</th>'
		+'							<th>视频位置</th>'
		+'							<th>缓存状态</th>'
		+'							<th>发布状态</th>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td>复制链接</td>'
		+'							<td>待缓存</td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td>复制链接</td>'
		+'							<td>待缓存</td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<table>'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>任务ID</th>'
		+'							<th>AssertID</th>'
		+'							<th>视频名称</th>'
		+'							<th>码率</th>'
		+'							<th>分辨率</th>'
		+'							<th>转码地址</th>'
		+'							<th>类型</th>'
		+'							<th>状态</th>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td></td>'
		+'							<td></td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td>ASERTEGERDFHH</td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td></td>'
		+'							<td></td>'
		+'							<td>未发布</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-tag">'
		+'					<span>标签名称<i class="tag-cross"></i></span>'
		+'					<span>标签名<i class="tag-cross"></i></span>'
		+'					<span>标签名称标签名称标签名称<i class="tag-cross"></i></span>'
		+'					<span>标签名<i class="tag-cross"></i></span>'
		+'					<span>标签<i class="tag-cross"></i></span>'
		+'					<span>标签<i class="tag-cross"></i></span>'
		+'					<span class="insert-add-tag" title="添加标签">+</span>'
		+'				</div>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();
	},

	_insertRow0113 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="13">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>基本信息</li>'
		+'			<li>影片信息</li>'
		+'			<li>视频信息</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">sdfsdf</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">北京频asdfasdf道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">多adsf屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">/chadd23423ddd_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">/c手动阀第三方.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">Bdd</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">北京ddd频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">多dd屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">栏目1：</div>'
		+'					<div class="insert-r">/channdd</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">发布状态：</div>'
		+'					<div class="insert-r">未发布</div>'
		+'					<div class="insert-row-btn btn">发布</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<table>'
		+'					<tbody>'
		+'						<tr>'
		+'							<th>AssertID</th>'
		+'							<th>视频位置</th>'
		+'							<th>码率</th>'
		+'							<th>分辨率</th>'
		+'							<th>视频编码</th>'
		+'							<th>音频编码</th>'
		+'							<th>封装格式</th>'
		+'							<th>视频状态</th>'
		+'							<th>发布状态</th>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td class="eps-cmt" title="ASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHH"><div>ASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHH</div></td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td>sfsdf</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>转码完成</td>'
		+'						</tr>'
		+'						<tr>'
		+'							<td>test</td>'
		+'							<td class="eps-cmt" title="ASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHH"><div>ASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHHASERTEGERDFHH</div></td>'
		+'							<td>好似扫荡手动阀</td>'
		+'							<td>1500</td>'
		+'							<td>1280*720</td>'
		+'							<td>setwe</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>IP_CDN</td>'
		+'							<td>转码完成</td>'
		+'						</tr>'
		+'					</tbody>'
		+'				</table>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();		
	},

	_insertRow0119 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="11">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>基本属性</li>'
		+'			<li>影片信息</li>'
		+'			<li>特征属性</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">sdfsdf</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频asdfasdf道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多adsf屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/chaddddnnel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/chanddnel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">Bdd</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京ddd频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多dd屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channddel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWYsdf.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">BTV文艺</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();
	},

	_insertRow0135 : function( row ){
		var self = this;
		var html = 
		'<tr class="insert-tr">'
		+'	<td class="insert-td" colspan="13">'
		+'		<ul class="insert-nav clearfix">'
		+'			<li>基本属性</li>'
		+'			<li>影片信息</li>'
		+'			<li>特征属性</li>'
		+'		</ul>'
		+'		<ul class="insert-pannel">'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">sdfsdf</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频asdfasdf道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多adsf屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/chaddddnnel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/chanddnel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">Bdd</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京ddd频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多dd屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channddel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWYsdf.png</div>'
		+'				</div>'
		+'			</li>'
		+'			<li>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道名：</div>'
		+'					<div class="insert-r">BTV文艺</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道类型：</div>'
		+'					<div class="insert-r">北京频道</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">平台属性：</div>'
		+'					<div class="insert-r">多屏</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">频道图片：</div>'
		+'					<div class="insert-r">/channel/image/BTVWY_888_666.jpg;</div>'
		+'				</div>'
		+'				<div class="insert-row">'
		+'					<div class="insert-l">台标：</div>'
		+'					<div class="insert-r">/channel/icon/BTVWY.png</div>'
		+'				</div>'
		+'			</li>'
		+'		</ul>'
		+'	</td>'
		+'</tr>';
		row.after( html );
		self._bindInsertNav();
	},

	_bindInsertNav : function(){
		var self = this;
		var nav = $('.insert-nav').children('li');
		var pannel = $('.insert-pannel').children('li');
		nav.eq(0).addClass('checked');
		pannel.eq(0).addClass('checked');

		nav.on('mouseenter', function(e){
			var _nav = $( e.currentTarget );
			if( _nav.hasClass('checked') ) return;
			nav.filter('.checked').removeClass('checked');
			pannel.filter('.checked').removeClass('checked');
			var index = _nav.index();
			pannel.eq( index ).addClass('checked');
			nav.eq( index ).addClass('checked');
		});
	}
	
};

return Table;

});